version: "3"
services:
    redis:
        image: redis
    url-shortener:
        image: url-shortener:latest
        environment: 
            - PORT=8080
            - REDIS_URL=redis://redis:6379
        depends_on:
            - redis
        ports:
            - 8080:8080
